---

- name: configure backup | {{ item.name }} | Create config folder
  file:
    state: directory
    path: /etc/duply
  tags:
    - duplicity
    - configure_backup

- name: configure backup | {{ item.name }} | Initiate config
  command: "duply {{ item.name }} create"
  args:
    creates: "/etc/duply/{{ item.name }}/conf"
  become: True
  tags:
    - duplicity
    - configure_backup

- name: configure backup | {{ item.name }} | Update config
  template:
      src: conf.j2
      dest: "/etc/duply/{{ item.name }}/conf"
  tags:
    - duplicity
    - configure_backup

- name: configure backup | {{ item.name }} | Excludes
  template:
    src: exclude.j2
    dest: "/etc/duply/{{ item.name }}/exclude"
  become: True
  tags:
    - duplicity
    - configure_backup

- name: "configure backup | {{ item.name }} | Cron: backup"
  cron:
    name: 'Duply backup {{ item.name }}'
    hour: 4
    minute: 0
    job: 'duply {{ item.name }} backup'
  tags:
    - duplicity
    - configure_backup

- name: "configure backup | {{ item.name }} | Cron: purge"
  cron:
    name: 'Duply full-purge {{ item.name }}'
    hour: 5
    minute: 0
    job: 'duply {{ item.name }} purgeFull --force'
  tags:
    - duplicity
    - configure_backup
