---

- name: configure backup | Create config folder
  file:
    state: directory
    path: /etc/duply

- name: configure backup | {{ item.name }} | Initiate config
  command: "duply {{ item.name }} create"
  args:
    creates: "/etc/duply/{{ item.name }}/conf"
  become: True
  tags:
    - duplicity
    - configure_backup

- name: configure backup | {{ item.name }} | Update config
  lineinfile:
    dest: "/etc/duply/{{ item.name }}/conf"
    regexp: '^{{ setting.key }}='
    line: '{{ setting.key }}={{ setting.value }}'
  become: True
  with_dict: "{{ item.settings }}"
  loop_control:
    loop_var: setting
  tags:
    - duplicity
    - configure_backup

- name: configure backup | {{ item.name }} | Excludes
  template:
    src: exclude.j2
    dest: "/etc/duply/{{ item.name }}/exclude"
  become: True
  tags:
    - duplicity
    - configure_backup

- name: configure backup | {{ item.name }} | Cron
  cron:
    name: 'Duply backup {{ item.name }}'
    hour: 4
    minute: 0
    job: 'duply {{ item.name }} backup'
  tags:
    - duplicity
    - configure_backup
