---

- name: Configure the Duplicity APT repository
  apt_repository:
    repo: ppa:duplicity-team/ppa
    state: present
  tags:
    - duplicity

- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - duplicity
    - duply
    - python-boto
  tags:
    - duplicity

- debug:
    var: aws_secret_access_key
  tags:
    - duplicity

- name: Configure backups
  include: configure_backup.yml
  with_items: "{{ duplicity_configs }}"
  tags:
    - duplicity
